DEBUG 2023-01-25 12:38:12.130 UTC: 	 CRAB Client version: v3.221018
DEBUG 2023-01-25 12:38:12.130 UTC: 	 Running on: Linux lxplus750.cern.ch 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-01-25 12:38:12.130 UTC: 	 Executing command: 'status'
DEBUG 2023-01-25 12:38:12.131 UTC: 	 Found CRAB cache file /afs/cern.ch/user/a/anpetkov/.crab3
ERROR 2023-01-25 12:38:12.134 UTC: 	 Error: crab_projects/crab_ParkingBPH1B_AOD_DATA_UL is not a valid CRAB project directory.
ERROR 2023-01-25 12:38:12.134 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_ParkingBPH1B_AOD_DATA_UL is not a valid CRAB project directory.
INFO 2023-01-25 12:38:12.142 UTC: 	 Log file is /eos/home-a/anpetkov/ElectronReconstructionUL_MyTool/CMSSW_12_0_0/src/Reco/RecoAnalyzer/crab.log
